name: Terraform AWS RDS Database Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the workflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository so Terraform can access the code

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use the desired version of Terraform

      # Step 3: Set up AWS credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use GitHub secret for AWS Access Key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use GitHub secret for AWS Secret Key
          aws-region: us-east-1  # Set the AWS region as needed

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init  # Initializes the Terraform working directory

      # Step 5: Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan  # Shows the execution plan

      # Step 6: Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply the changes to create the RDS instance

     # - name: Output DB Endpoint
     #   run: echo "Database endpoint: $(terraform output -raw db_endpoint)"
